export const auth = {
    ico_google: require('../../assets/images/auth/ico_google.png'),
    ico_facebook: require('../../assets/images/auth/ico_facebook.png'),
    ico_apple: require('../../assets/images/auth/ico_apple.png'),
    ico_fb: require('../../assets/images/auth/ico_fb.png'),
    ico_youtube: require('../../assets/images/auth/ico_youtube.png'),
    ico_tiktok: require('../../assets/images/auth/ico_tiktok.png'),
    ico_website: require('../../assets/images/auth/ico_website.png'),
    ico_link: require('../../assets/images/auth/ico_link.png'),
    ico_trash: require('../../assets/images/auth/ico_trash.png'),
    ico_upfile: require('../../assets/images/auth/ico_upfile.png'),
    ico_file_uploaded: require('../../assets/images/auth/ico_file_uploaded.png'),
    ic_phone_otp: require('../../assets/images/auth/ic_phone_otp.png'),
    ic_mail_otp: require('../../assets/images/auth/ic_mail_otp.png'),
};