export const bottomTab = {
    home_active: require('../../assets/images/bottom-tab/home_active.png'),
    home_unactive: require('../../assets/images/bottom-tab/home_unactive.png'),
    nearby_active: require('../../assets/images/bottom-tab/nearby_active.png'),
    nearby_unactive: require('../../assets/images/bottom-tab/nearby_unactive.png'),
    course_active: require('../../assets/images/bottom-tab/course_active.png'),
    course_unactive: require('../../assets/images/bottom-tab/course_unactive.png'),
    account_active: require('../../assets/images/bottom-tab/account_active.png'),
    account_unactive: require('../../assets/images/bottom-tab/account_unactive.png'),
    btn_assitant: require('../../assets/images/bottom-tab/drassistant.png'),
    community: require('../../assets/images/bottom-tab/community.png'),
    newsfeed_active: require('../../assets/images/bottom-tab/newsfeed_active.png'),
    newsfeed_unactive: require('../../assets/images/bottom-tab/newsfeed_unactive.png'),
    carely: require('../../assets/images/bottom-tab/carely.png'),
    menu_active: require('../../assets/images/bottom-tab/menu_active.png'),
    menu_unactive: require('../../assets/images/bottom-tab/menu_unactive.png'),
    menu_line: require('../../assets/images/bottom-tab/menu_line.png'),
    carely_home_active: require('../../assets/images/bottom-tab/carely_home_active.png'),
    carely_home_unactive: require('../../assets/images/bottom-tab/carely_home_unactive.png'),
    drnetwork: require('../../assets/images/bottom-tab/drnetwork.png'),
    appointment_active: require('../../assets/images/bottom-tab/appointment_active.png'),
    appointment_unactive: require('../../assets/images/bottom-tab/appointment_unactive.png'),
    carely_account: require('../../assets/images/bottom-tab/carely_account.png'),
};