export const global = {
    // img_default: require('../../assets/images/global/img_default_1.png'),
    // channel_default: require('../../assets/images/global/channel_default.png'),
    // empty_search: require('../../assets/images/global/empty_search.png'),
    // app_title: require('../../assets/images/global/app_title.png'),
    // no_avatar: require('../../assets/images/global/no_avatar.png'),
    // complete: require('../../assets/images/global/complete.png'),
    // logo_hear: require('../../assets/images/global/logo_heart.png'),
    // ico_notify: require('../../assets/images/global/ico_notify.png'),
    // ico_search: require('../../assets/images/global/ico_search.png'),
    // ico_location_hospital: require('../../assets/images/global/ico_location_hospital.png'),
    // ico_edit: require('../../assets/images/global/ic_edit.png'),
    // ic_search_white: require('../../assets/images/global/ic_search_white.png'),
    // ic_comment: require('../../assets/images/global/ic_comment.png'),
    // ico_send: require('../../assets/images/global/ico_send.png'),
    // ic_assitant: require('../../assets/images/global/ic_assitant.png'),
    // swipe: require('../../assets/images/global/swipe.png'),
    // tour_up: require('../../assets/images/global/tour_up.png'),
    // tour_down: require('../../assets/images/global/tour_down.png'),
    // dn_default: require('../../assets/images/global/dn_default.jpg'),
    // bg_package: require('../../assets/images/global/bg_package.png'),
    // bg_package_carely: require('../../assets/images/global/bg_package_carely.png'),
    // no_internet: require('../../assets/images/global/no_internet.png'),
};