export const newsfeed = {
    ico_emoij: require('../../assets/images/newsfeed/ico_emoij.png'),
    ico_media: require('../../assets/images/newsfeed/ico_media.png'),
    ico_tag: require('../../assets/images/newsfeed/ico_tag.png'),
    ico_messenger: require('../../assets/images/newsfeed/ico_messeger.png'),
    ico_zalo: require('../../assets/images/newsfeed/ico_zalo.png'),
    ico_mess: require('../../assets/images/newsfeed/ico_mes.png'),
    ico_link: require('../../assets/images/newsfeed/ico_link.png'),
    icon_deleteComment: require('../../assets/images/newsfeed/icon_deleteComment.png'),
    ico_comment: require('../../assets/images/newsfeed/ico_comment.png'),
    ico_channel: require('../../assets/images/newsfeed/ico_channel.png'),
    ico_ai: require('../../assets/images/newsfeed/ico_ai.png'),
    ico_aiCre: require('../../assets/images/newsfeed/ico_aiCreate.png'),
    ico_send: require('../../assets/images/newsfeed/ico_send.png'),
    ico_baseline_loop: require('../../assets/images/newsfeed/ic_baseline-loop.png'),
    ico_aiImg: require('../../assets/images/newsfeed/ico_aiImg.png'),
};