export const profile = {
  ico_EmptyVideos: require('../../assets/images/profile/ico_emptyVideo.png'),
  ico_EmptyBook: require('../../assets/images/profile/ico_emptybook.png'),
  ico_EmptyBooking: require('../../assets/images/profile/ico_emptyBookings.png'),
  ico_emptyCard: require('../../assets/images/profile/ico_emptyCard.png'),
  ico_tym: require('../../assets/images/profile/ico_tym.png'),
  ico_success: require('../../assets/images/profile/ico_success.png'),
  ico_card_user: require('../../assets/images/profile/ico_card-user.png'),
  ico_unable: require('../../assets/images/profile/ico_unable.png'),
  ico_logo: require('../../assets/images/profile/ico_logo.png'),
  ico_logo1: require('../../assets/images/profile/ico_logo1.png'),
  ico_userGroup: require('../../assets/images/profile/ico_userGroup.png'),
  ico_frame: require('../../assets/images/profile/ico_frame.png'),
  ico_doc: require('../../assets/images/profile/ico_doc.png'),
  bg_course: require('../../assets/images/profile/bg_course.png'),
  bg_popup: require('../../assets/images/profile/bg_popup.png'),
};
