org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

org.gradle.daemon=true

android.useAndroidX=true

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

newArchEnabled=true

hermesEnabled=true

edgeToEdgeEnabled=false

# Khong nen bat neu project qua nhieu native, Sau vài tháng stable thi bat caching=true
#org.gradle.parallel=true
#org.gradle.caching=true
#org.gradle.configureondemand=true