export const ADJUST_EVENT = {
  onboarding_skipped: 'vu0h8g',
  onboarding_started: '3zrxtj',
  registration_started: '39546a',
  interest_selection_skipped: 'vqksoe',
  user_type_doctor: 'upphff',
  user_type_enduser: '5bv1i9',
  user_type_medicalstudent: 'h9jbmz',
  registration_completed: '2ydwsc',
  login: '6s0p7j',
  logout: 'g733lk',
  home_button_clicked: 'mtwhs2',
  community_button_clicked: 'e92yu3',
  course_button_clicked: 'mbln6p',
  da_button_clicked: 'ham3qn',
  nearby_button_clicked: 'vveyd0',
  home_search: 'fvxsj8',
  home_banner_click: 'vkltt3',
  home_banner2_click: 'uwnren',
  home_banner3_click: '5h2tjd',
  home_banner2_impression: 'q2nct8',
  home_banner3_impression: 'jlhf77',
  course_banner_click: '2funec',
  course_banner2_click: 'p516q3',
  course_banner3_click: 'io0eqm',
  course_banner2_impression: 'nh4570',
  course_banner3_impression: '1ll0rx',
  group_joined: 'imu56k',
  group_left: 'jnzxun',
  group_content_viewed: 'frd4e2',
  group_reaction_added: 'cdsexz',
  course_detail_viewed: 'oqvhi3',
  course_lesson_opened: '8a8tw0',
  course_completed: 'abb44y',
  course_review_submitted: 'g827sb',
  course_purchased: 'dxdoy9',
  course_payment_cancelled: 'ilmcay',
  course_payment_failed: 'ijem9u',
  dn_open_app: 'yrzv15',
  delete_account: '2jbq99',
  newsfeed_button_clicked: 'bq0zsy',
  newsfeed_banner_click: 'r7f1wp',
  newsfeed_banner2_click: 'aw28v8',
  newsfeed_banner3_click: 'ysy9ai',
  newsfeed_banner2_impression: 'mf8wl4',
  newsfeed_banner3_impression: 'x0a52j',
  nearby_banner_click: 'qgf8b3',
  nearby_banner2_click: 'b3f1i2',
  nearby_banner3_click: 'pn7e1r',
  nearby_banner2_impression: '8ax8ll',
  nearby_banner3_impression: '2zj7e2',
  community_banner_click: 'sh564t',
  community_banner2_click: 'yt0jge',
  community_banner3_click: 'xsiq2w',
  community_banner2_impression: '149h1x',
  community_banner3_impression: 'wz7flv',
  video_click: 'ynwhpa',
  video_detail_scroll: '3w993r',
};

export const ADJUST_CAMPAIGN = {
  go_screen: 'go_screen',
};

export const ADJUST_DEEPLINK = {
  home_screen: 'home',
  nearby_screen: 'nearby',
  newsfeed_screen: 'newsfeed',
  newsfeed_detail_screen: 'newsfeed_detail',
  course_screen: 'course',
  community_screen: 'community',
  course_detail_screen: 'course_detail',
  video_detail_screen: 'video_detail',
  community_detail_screen: 'community_detail',
  channel_detail_screen: 'channel_detail',
  video_discovery_screen: 'video_discover',
  search_screen: 'search',
};

export const CAMPAIGN = {
  go_screen: 'go_screen',
};

export const DEEPLINK = {
  community_detail_screen: 'rooms',
  video_detail_screen: 'VIDEO_PLAY_LIST',
  video_screen: 'video',
  newsfeed_detail_screen: 'newsfeed',
  channel_detail_screen: 'channel_detail',
  channel_screen: 'channels',
  doctor_detail_screen: 'doctor_detail',
  package_detail_screen: 'package_detail',
  package_carely_detail_screen: 'package_carely_detail_screen',
  course_detail_screen: 'course_detail_screen',
};
