export const STORAGEKEY = {
  CATEGORIES: 'CATEGORIES',
  CATEGORIES_CHOOSE: 'CATEGORIES_CHOOSE',
  JWT_TOKEN: 'JWT_TOKEN',
  LANGUAGE: 'LANGUAGE',
  GETTING_APP: 'GETTING_APP',
  SHOW_CATEGORY: 'SHOW_CATEGORY',
  FIREBASE_TOKEN: 'FIREBASE_TOKEN',
  // home
  INTERESTS_CHOOSED: 'Interests_choosed INTERESTS_CHOOSED',
  SEARCH_HISTORY: 'SEARCH_HISTORY',
  ALLOW_TRACKING: 'ALLOW_TRACKING',
  FIREBASE_CONFIG: 'FIREBASE_CONFIG',
  PLAY_TEXT: 'PLAY_TEXT',
  FIREBASE_DYNAMIC_LINK: 'FIREBASE_DYNAMIC_LINK',
  // community
  LIST_MESSAGES: 'LIST_MESSAGES',
  ID_MESSAGE: 'ID_MESSAGE',
  LIST_ROOM: 'LIST_ROOM',
  CHECKLOCAL_FIRST: 'CHECKLOCAL_FIRST',
  CHECK_ONL: 'CHECK_ONL',
  CHECK_DISONL: 'CHECK_DISONL',
  AVATAR_LOCAL: 'AVATAR_LOCAL',
  CHECK_FILE: 'CHECK_FILE',
  DELETE_CHAT: 'DELETE_CHAT',
  PIN_LOCAL: 'PIN_LOCAL',
  CHECK_GROUP_PRIVATE: 'CHECK_GROUP_PRIVATE',
  //Region
  REGION: 'REGION',
  APP_BG_CHAT: 'APP_BG_CHAT',
  JOIN_PUBLIC_CHAT: 'JOIN_PUBLIC_CHAT',
  //Video Config
  VIDEO_CONFIG: 'VIDEO_CONFIG',
  CHECK_CAMERA_LIVE: 'CHECK_CAMERA_LIVE',
  //
  TOUR_GUIDE: 'TOUR_GUIDE',
  LIST_USER_BLOCK: 'LIST_USER_BLOCK',
  LIST_ROOM_PACKAGE: 'LIST_ROOM_PACKAGE',
  CARELY_ADDRESS_HISTORY: 'CARELY_ADDRESS_HISTORY',
  // Service free, chi cho book 1 lan
  CARELY_SERVICE_FREE: 'CARELY_SERVICE_FREE',
  SEARCH_HISTORY_CARELY: 'SEARCH_HISTORY_CARELY',
  //
  PAYMENT_PENDING_KEY: 'PAYMENT_PENDING',
  LOCATION_ADDRESS_HISTORY: 'LOCATION_ADDRESS_HISTORY',
};
