export enum notifyType {
  system = 'system',
  promotion = 'promotion',
  new = 'new',
  like = 'like',
  comment = 'comment',
  like_comment = 'like_comment',
  reply_comment = 'reply_comment',
  follow = 'follow',
  booking = 'booking',
  confirm_booking = 'confirm_booking',
  cancel_booking = 'cancel_booking',
  next_booking = 'next_booking',
  m_voucher = 'm_voucher',
  link = 'link',
  kyc_approved = 'kyc_approved',
  kyc_rejected = 'kyc_rejected',
  chat = 'chat',
  chat_friend = 'friend',
  live = 'live',
  live_start = 'live_start',
  //
  on_the_way_booking = 'on_the_way_booking',
  arrived_booking = 'arrived_booking',
  completed_booking = 'completed_booking',
  expired_booking = 'expired_booking',
}
