export const STORAGEKEY = {
  CATEGORIES: 'CATEGORIES',
  CATEGORIES_CHOOSE: 'CATEGORIES_CHOOSE',
  JWT_TOKEN: 'JWT_TOKEN',
  LANGUAGE: 'LANGUAGE',
  GETTING_APP: 'GETTING_APP',
  SHOW_CATEGORY: 'SHOW_CATEGORY',
  FIREBASE_TOKEN: 'FIREBASE_TOKEN',
};
